# Generated by Django 5.2.12 on 2026-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Representante"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        max_length=300, verbose_name="Empresa / Institucion"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(max_length=50, verbose_name="WhatsApp / Telefono"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Corporativo"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logistica", "Logistica"),
                            ("restaurante", "Restaurante"),
                            ("salud", "Salud"),
                            ("otro", "Otro"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Tipo de Proyecto",
                    ),
                ),
                (
                    "investment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("menos-5k", "Menos de $5,000 USD"),
                            ("5k-15k", "$5,000 - $15,000 USD"),
                            ("15k-30k", "$15,000 - $30,000 USD"),
                            ("mas-30k", "Mas de $30,000 USD"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Rango de Inversion",
                    ),
                ),
                ("message", models.TextField(verbose_name="Necesidad / Mensaje")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de contacto"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leido")),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
