# Generated by Django 5.2.12 on 2026-05-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("logistica", "Logística"),
                    ("salud", "Salud"),
                    ("gastronomia", "Gastronomía"),
                    ("tecnologia", "Tecnología"),
                    ("otro", "Otro"),
                ],
                default="",
                max_length=30,
                verbose_name="Sector Industrial",
            ),
        ),
    ]
