# Generated by Django 5.2.12 on 2026-05-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="WhatsApp / Telefono",
            ),
        ),
    ]
