# Generated by Django 5.2.12 on 2026-06-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_whatsapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(max_length=500, verbose_name="Pagina visitada"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Referrer"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Pais"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Region"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Ciudad"
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(default=False, verbose_name="Consentimiento"),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de visita"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "ordering": ["-visited_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="consent_given",
            field=models.BooleanField(
                default=False, verbose_name="Consentimiento cookies"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="referrer",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Referrer"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="user_agent",
            field=models.TextField(blank=True, default="", verbose_name="User Agent"),
        ),
    ]
